Vagrant.configure(2) do |config|
	config.vm.box = "micaja09_ubuntu_precise32"
	config.vm.network "forwarded_port", guest: 80, host: 8080
	config.vm.provision :shell, :path=>"install_apache.sh"
	
	config.vm.provision :puppet do |puppet|
		puppet.manifest_file = "vagpuppet.pp"
	end
end
